Data quality and data governance quality introduction
aureliusenterprise/doc_demo_environment pull request #18
Opened 2022-09-27 07:26 UTC by thijs-franck

Added an introduction for the data quality and data governance quality sections

2022-09-27 13:53 UTC, AmericoChiclana requested changes

2022-09-27 13:53 UTC, AmericoChiclana commented on DOc/docs/source/Options/user-story-5.rst
> +When first starting to set up a data management organisation, there are a lot of different aspects to consider.
When setting up a data management organisation for the first time.

2022-09-27 13:53 UTC, AmericoChiclana commented on DOc/docs/source/Options/user-story-5.rst
> +The data governance organisation needs to be set up.
delete this sentence is redundant

2022-09-27 13:53 UTC, AmericoChiclana commented on DOc/docs/source/Options/user-story-5.rst
> +Keeping an overview of the organisation's progress in all these activities can be a challenge.
overview of the model progress can be challenging

2022-09-27 13:53 UTC, AmericoChiclana commented on DOc/docs/source/Options/user-story-5.rst
> +The Aurelius Atlas tool lets key stakeholders monitor the progress of the implementation, as well as the overall data governance quality.
the entire progress of the implementation, as well of the overall data.....

2022-09-27 13:53 UTC, AmericoChiclana commented on DOc/docs/source/Options/user-story-5.rst
> +It also allows for better decision making on where to focus for the next improvement.
It allows you to make better decisions and clarifies what to focus on for a next  improvement

2022-09-27 13:53 UTC, AmericoChiclana commented on DOc/docs/source/Options/user-story-5.rst
> +All compliant and non-compliant rules are counted, and the ratio determines an overall data governance quality score.
delete the coma after counted

2022-09-27 13:53 UTC, AmericoChiclana commented on DOc/docs/source/Options/user-story-4.rst
> +Meanwhile, bad data quality limits the value of data, and results in worse business outcomes.
delete the coma after data

2022-09-27 13:53 UTC, AmericoChiclana commented on DOc/docs/source/Options/user-story-4.rst
> +Improving the data quality of manually entered data tends to involve the education of people and process improvements.
put a coma after "entered data"

2022-09-27 13:53 UTC, AmericoChiclana commented on DOc/docs/source/Options/user-story-4.rst
> +Aurelius Atlas allows for the discovery and insight of your organisation's data quality across data sources.
just organisation without the apostrophe

2022-09-27 13:53 UTC, AmericoChiclana commented on DOc/docs/source/Options/user-story-4.rst
> +The tool also allows the people responsible for data quality to do root cause analysis of data quality issues.
put a coma after "data quality, to do a root"

2022-09-28 11:44 UTC, wombach requested changes

2022-09-28 11:44 UTC, wombach commented on DOc/docs/source/Options/user-story-4.rst
> +For every rule, a percentage score is assigned.
For every rule, a percentage score is calculated by dividing the number of compliant entities over the number of all entities,

2022-09-28 11:44 UTC, wombach commented on DOc/docs/source/Options/user-story-4.rst
This is a detail/lengthy introduction of what data governance is and how we look at it. The first two sentences state what is the problem, the subsequent sentence states why it is a problem. The rest addresses how we solve the problem.
Can you add some more details on why it is a problem. What are the consequences if data quality is bad?
AT the end I am missing a description of a short scenario: Something like a data engineer has found the dataset NL1-HR-001 <add link> and wants to understand the data quality of the dataset.

2022-09-28 11:44 UTC, wombach commented on DOc/docs/source/Options/user-story-5.rst
> +The data governance organisation needs to be set up.
> delete this sentence is redundant

I disagree: data management and data governance organization are two fundamental different things! Please keep the sentence

2022-09-28 11:44 UTC, wombach commented on DOc/docs/source/Options/user-story-5.rst
AT the end I am missing a description of a short scenario: Something like a data scientist is looking for some trustworthy data for a specific topic. Already during the selection of relevant dataset he wants to have an indication on the data quality of the dataset. This should set the scene for the walk through example.

2022-09-29 07:20 UTC, wombach approved these changes

2022-09-29 11:00 UTC, gabypascha commented on DOc/docs/source/Options/user-story-4.rst
> +Good data quality helps make data more useful and usable, resulting in better business outcomes.
and reliable

2022-09-29 11:00 UTC, gabypascha commented on DOc/docs/source/Options/user-story-4.rst
> +This can lead to ineffective decision making and a waste of time and resources.
change the first and to ,

2022-09-29 11:07 UTC, merged